Locale: en # Localisation

EnableRespawn: false # Enable respawn buffs

EnableRespawnStrength: true # Enable strength effect on respawn
StrengthDuration: 30 # Respawn strength duration
StrengthAmplitude: 1 # Respawn strength level - 1 (Ex: 1 => Strength 2)
EnableRespawnSpeed: true # Enable speed effect on respawn
SpeedDuration: 30 # Respawn speed duration
SpeedAmplitude: 1 # Respawn speed level - 1 (Ex: 1 => Speed 2)
EnableRespawnResistance: true # Enable resistance effect on respawn
ResistanceDuration: 30 # Respawn resistance duration
ResistanceAmplitude: 5 # Respawn resistance level - 1 (Ex: 5 => Resistance 6)

# Respawn with an item in your main hand
RespawnMainHand:
  Use: true # Enable
  Item: STICK # Item type
  Name: "Marine's Repelling Twig" # Name of item
  Lore:
    - "Marine's Repelling Twig" # Lore of item
  Enchants: # List of enchantments and their levels
    KNOCKBACK: 3
    DAMAGE_ALL: 5

# Respawn with an item in your off hand
RespawnOffHand:
  Use: false # Enable
  Item: SHIELD # Item type
  Name: "Marine's Defense Shield" # Name of item
  Lore:
    - "Marine's Defense Shield" # Lore of item
  Enchants: # List of enchantments and their levels
    DURABILITY: 3

EnableCrewSigns: true # Enable Crew: signs
SetHomeToCrewSign: false # Set player's essentials home to priority bed when shift right clicked